-- ps-mdt penal code seed (State of San Andreas Penal Code, V. 31-MAY-2026)
-- Idempotent: clears the table then re-inserts every charge.
DELETE FROM mdt_penal_codes;
INSERT INTO mdt_penal_codes (code,label,charge_class,months,fine,description) VALUES
('VC01','Speeding 1st Degree','infraction',0,1000,'Operating a vehicle at speeds exceeding limits by 1-20 km/h on public roads.'),
('VC02','Speeding 2nd Degree','infraction',0,2000,'Operating a vehicle at speeds exceeding limits by 21-40 km/h on public roads.'),
('VC03','Speeding 3rd Degree','infraction',0,3500,'Operating a vehicle at speeds exceeding limits by 41-80 km/h on public roads.'),
('VC04','Illegal Parking','infraction',0,500,'Parking or leaving a vehicle where parking is prohibited (no-parking zones, crosswalks, hydrants, blocking traffic, etc.).'),
('VC05','Improper Traffic Maneuvers','infraction',0,500,'Illegal U-turns, failing to maintain a lane, tailgating, or failure to yield at traffic control devices.'),
('VC06','Following or Impeding Emergency Response','infraction',0,1000,'Failure to yield to emergency vehicles, or following/impeding them without legal justification.'),
('VC07','Operating a Vehicle Without A License On Your Person','infraction',0,500,'Driving without the proper licensing on your person.'),
('VC08','Negligent Operation of a Road or Marine Vehicle','infraction',0,1500,'Failing to use reasonable care while operating a vehicle, risking injury or damage.'),
('VC09','Blocking Intersection','infraction',0,500,'Stopping, parking or obstructing an intersection.'),
('VC10','Unroadworthy Vehicle','infraction',0,500,'Operating a vehicle that fails Minimum Safety Requirements (lights, mirrors, registration, etc.).'),
('VC11','Failure to Pay a Toll','infraction',0,3000,'Passing through a toll without paying.'),
('VC12','Operating an Unregistered Vehicle','infraction',0,1000,'Driving a vehicle not legally purchased or not registered with the State of San Andreas.'),
('VC13','Disruptive Impeding or Blocking Travel','infraction',0,2000,'Driving so slowly as to impede or block the normal flow of traffic without cause.'),
('VC14','Operation of a Vehicle without a License Plate','infraction',0,1000,'Operating a vehicle without a valid state-issued plate (use VM09 if during another crime).'),
('GC01','Loitering','infraction',0,750,'Remaining in an area or building after being asked to leave by management or a government employee.'),
('GC02','Traffic Endangerment','infraction',0,500,'Creating hazards or endangering drivers, self, or pedestrians on roadways; jaywalking.'),
('GC03','Disorderly Conduct','infraction',0,5000,'Disruptive public behaviour: excessive noise, climbing on vehicles, tripping/tackling, misuse of horn, crowding a person.'),
('GC04','Face Concealment','infraction',0,500,'Wearing facial concealment in public without lawful exemption.'),
('GC05','Misuse of Government Public Safety Radio Frequencies or Hotlines','infraction',0,1000,'Disrupting or improperly using public safety radio frequencies or emergency hotlines for non-emergencies.'),
('GC06','Possession of Cannabis','infraction',0,1000,'Possessing small amounts of cannabis (up to 7g processed / 10 plants / any seeds) without a valid medical license.'),
('GM01','Assault','misdemeanor',10,1500,'The threat of bodily harm with intention, creating reasonable fear of imminent harm. (Weapon lic: Revoked)'),
('GM02','Battery','misdemeanor',20,2000,'Willful and unlawful physical contact, use of force, or violence upon another. (Weapon lic: Revoked)'),
('GM03','Possession of a Blade','misdemeanor',10,1000,'Carrying a fixed/assisted blade over 3 inches capable of serious injury. (Weapon lic: Revoked)'),
('GM04','Resisting Arrest','misdemeanor',25,2000,'Resisting arrest physically or by running on foot.'),
('GM05','Receiving Stolen Property','misdemeanor',10,1000,'Buying, receiving, concealing, or selling stolen property.'),
('GM06','Petty Theft','misdemeanor',15,2000,'Taking another person''s property without consent, value less than $5,000.'),
('GM07','Criminal Fraud','misdemeanor',20,1500,'Intentional deception for personal/financial gain causing >= $5,000 in damages. (Weapon lic: Revoked)'),
('GM08','Vandalism','misdemeanor',15,1000,'Maliciously defacing, damaging, or destroying property not your own.'),
('GM09','Vigilantism','misdemeanor',15,1000,'A non-law-enforcement person attempting to enforce laws. (Weapon lic: Revoked)'),
('GM10','Failure to Comply / Identify','misdemeanor',20,1000,'Failure to comply with a lawful command or identify yourself during an investigation.'),
('GM11','Predatory Lending','misdemeanor',15,2000,'Loaning money under unfair or fraudulent pretenses, often with threat of violence.'),
('GM12','Giving False Information to a Police Officer','misdemeanor',20,1000,'Giving fake information or documents to a police officer. (Weapon lic: Revoked)'),
('GM13','Criminal Threats','misdemeanor',20,1000,'Knowingly threatening the life or bodily harm of another or their loved ones. (Weapon lic: Revoked)'),
('GM14','Obstruction of Justice','misdemeanor',25,1000,'Interfering with, delaying, lying to, or concealing information from a lawful investigation.'),
('GM15','Animal Cruelty','misdemeanor',25,1000,'Causing severe harm or neglect to any animal (excludes legal hunting). (Weapon lic: Revoked)'),
('GM16','Failure to Pay a Fine','misdemeanor',15,1000,'Failing to pay a fine for longer than the allowed 7 days.'),
('GM17','Bribery','misdemeanor',30,1000,'Offering, giving, soliciting, or receiving value to influence official actions.'),
('GM18','Looting of a Dead Human Body','misdemeanor',20,1750,'Unlawfully removing or adding items to a dead human body or its vicinity. (Weapon lic: Revoked)'),
('GM19','Face Concealment (b)','misdemeanor',10,500,'Concealing identity with a mask while intimidating others or committing a crime.'),
('GM20','Minor Sales Tax Evasion','misdemeanor',20,5000,'Failing to report/pay sales tax (5%), pocketing it; under $50,000 total tax. (Fine: $5,000 + unpaid tax +10%)'),
('GM21','False Imprisonment','misdemeanor',30,2000,'Unlawfully restraining, detaining, or confining another without consent. (Weapon lic: Revoked)'),
('GM22','Contempt of Court','misdemeanor',30,2500,'Minor willful disobedience or misconduct in the presence of a court.'),
('GM23','Parole Violation','misdemeanor',30,10000,'Any violation of parole conditions (new crimes, tampering with tracking, missed meetings, etc.).'),
('GM24','Contempt of Congress','misdemeanor',30,10000,'Disrespect, interference, or non-compliance with Congress; requires Speaker/Chair/Prosecutor authorization.'),
('GM25','Possession/Unlawful use of Government Equipment','misdemeanor',25,1500,'Possessing or using unlawfully obtained government equipment (stingers, tazers, jammers, encrypted radios).'),
('GM26','Possession of Illegal Information Gathering Devices','misdemeanor',15,1000,'Possessing equipment to infiltrate government radio frequencies or GPS systems.'),
('GM27','Incitement of Violence against a Peace Officer','misdemeanor',25,2000,'Advocating the imminent unlawful killing/injuring of a peace officer (upgrades to GF27 if it causes harm).'),
('GM28','Transfer/Smuggling of External Goods into Correctional Facilities','misdemeanor',30,5000,'Transferring or concealing unauthorized external goods into DOC custody/facilities.'),
('NM01','Inciting a Riot','misdemeanor',45,2500,'The attempt or fulfillment of causing a riot.'),
('NM02','Participating in a Riot','misdemeanor',30,2000,'Two or more people using force/violence, disturbing the peace, or threatening immediate force.'),
('NM03','Unlawful Assembly','misdemeanor',15,1000,'Two or more people gathering to do something illegal or disobeying law enforcement instruction.'),
('NM04','Stalking','misdemeanor',30,2500,'Repeated unwanted contact/communication making someone fear for their safety. (Weapon & Pilot lic: Revoked)'),
('NM05','Public Intoxication','misdemeanor',15,0,'Being intoxicated in public, unable to care for own safety or being a nuisance.'),
('NM06','Trespassing','misdemeanor',15,1500,'Entering/remaining on private or restricted government property without permission.'),
('NM07','Prostitution, Pimping or Pandering','misdemeanor',25,1000,'Engaging in or facilitating sex for payment.'),
('NM08','Abuse of Government Public Safety Radio Frequencies or Hotlines','misdemeanor',10,1500,'Knowingly misusing/obstructing public safety radio or emergency hotlines.'),
('NM09','Harassment','misdemeanor',20,2000,'Repeated unwelcome actions intended to scare, alarm, or distress a person (incl. via SMS/social media).'),
('NM10','Disturbing the Peace','misdemeanor',10,1000,'Performing at least two disruptive public acts (noise, climbing vehicles, crowding, etc.).'),
('NM11','Public Lewdness','misdemeanor',10,1500,'Indecent exposure or sexual conduct in a public place where others may be offended.'),
('VM01','Operating a Vehicle without a Valid License','misdemeanor',10,2000,'Driving without the proper driver''s/trucker''s license.'),
('VM02','Operating a Vehicle with a Suspended License','misdemeanor',25,1500,'Driving while privileges are revoked/suspended.'),
('VM03','Reckless Operation of a Road or Marine Vehicle','misdemeanor',20,3000,'Intentional disregard for life/property while operating a vehicle.'),
('VM05','Drunk, Impaired, or Distracted Driving','misdemeanor',30,2000,'Operating a vehicle while intoxicated (BAC > 0.08%), impaired, or distracted.'),
('VM06','Street Competition','misdemeanor',30,2000,'Planned, organized illegal street contests (races, drift contests).'),
('VM07','Hit and Run','misdemeanor',15,2500,'Causing a property-damage accident then fleeing without exchanging details.'),
('VM08','Vehicle Registration Fraud','misdemeanor',15,2000,'Operating/possessing/selling a vehicle with counterfeit or another vehicle''s plates.'),
('VM09','Operation of a Vehicle without a License Plate','misdemeanor',10,1750,'Operating without a valid plate during the commission of another crime.'),
('VF01','Evading an Officer','felony',60,3000,'Willfully fleeing or eluding a pursuing law enforcement officer. (Weapon lic: Revoked)'),
('VF02','Felony Hit and Run','felony',75,3000,'Causing an injury/death accident then failing to remain, render aid, or notify services. (Weapon lic: Revoked)'),
('VF03','Operating a Chop Shop','felony',60,4000,'Owning or operating a chop shop profiting from illegal modification sales. (Weapon lic: Revoked)'),
('VF04','Felony Public Endangerment','felony',60,3000,'Placing the public in acute danger through unsafe operation of a vehicle, firearm, etc. (Weapon lic: Revoked)'),
('DM01','Possession of a Schedule I Controlled Substance','misdemeanor',20,2500,'Possessing a Schedule I substance (heroin, meth, cocaine, crack).'),
('DM02','Possession of a Schedule II Controlled Substance','misdemeanor',15,2000,'Possessing a Schedule II substance (LSD, MDMA/ecstasy).'),
('DM03','Possession of a Schedule III Controlled Substance','misdemeanor',10,1500,'Possessing a Schedule III substance (cannabis, steroids, psilocybin, methadone).'),
('DM04','Possession of a Controlled Substance while Armed','misdemeanor',25,3000,'Possessing any controlled substance while armed with a firearm. (Weapon lic: Revoked)'),
('DM05','Possession of Drug Paraphernalia','misdemeanor',15,1500,'Possessing equipment/precursors intended for manufacturing or using controlled substances.'),
('DM06','Cultivation of a Controlled Substance','misdemeanor',30,3000,'Gathering, growing, or possessing plants/elements to create controlled substances.'),
('DM07','Possession of a Controlled Substance/Drug Paraphernalia within a Correctional Facility','misdemeanor',30,3000,'Taking possession of drugs or paraphernalia while in DOC custody.'),
('DF01','Possession of a Controlled Substance with Intent of Sales','felony',45,3000,'Possessing > 1 oz (28g) or packaged for sale. (Weapon lic: Revoked)'),
('DF02','Sale of a Controlled Substance','felony',60,3000,'Selling, distributing, or delivering a controlled substance. (Weapon lic: Revoked)'),
('DF03','Sale of Drug Paraphernalia','felony',45,2500,'Selling or distributing drug paraphernalia/precursors. (Weapon lic: Revoked)'),
('DF04','Trafficking a Controlled Substance','felony',60,3000,'Possessing > 3 oz (84g) of a controlled substance. (Weapon lic: Revoked)'),
('DF05','Manufacturing a Controlled Substance','felony',60,5000,'Producing, preparing, or processing chemicals to create controlled substances. (Weapon lic: Revoked)'),
('DF06','Unlawful Administering of Drugs','felony',45,3000,'Poisoning food/water or administering a substance against the receiving party''s wishes.'),
('DF07','Transfer/Smuggling of Controlled Substances into Correctional Facilities','felony',80,5000,'Transferring or smuggling controlled substances/paraphernalia into or out of DOC.'),
('WM01','Unlawful Brandishing of a Firearm or Weapon','misdemeanor',15,2000,'Drawing, exhibiting, or using a firearm/weapon without lawful reason. (Weapon lic: 1 Day Suspension)'),
('WM02','Possession of a Class 1 Firearm','misdemeanor',30,2000,'Unlicensed/illegal possession of a Class 1 firearm (semi-automatic handgun), parts, or ammo. (Weapon lic: Revoked)'),
('WM03','Criminal Use of Weapon Modifications','misdemeanor',25,1500,'Possessing/using illegal weapon modifications (extended mags, suppressors, sights, etc.). (Weapon lic: Revoked)'),
('WM04','Possession of Illegal Body Armor','misdemeanor',20,2000,'Possessing illegal body armor not obtained through legal traders.'),
('WM05','Possession of Body Armor as a Felon','misdemeanor',25,2000,'Possessing body armor while a convicted felon or while committing a felony.'),
('WF01','Assault with a Deadly Weapon','felony',45,3000,'Threat of bodily harm creating fear of imminent harm through a deadly weapon. (Weapon lic: Revoked)'),
('WF02','Shooting from a Vehicle (Drive-By)','felony',80,3000,'Discharging a firearm/weapon from a vehicle or aircraft. (Weapon lic: Revoked)'),
('WF03','Possession of a Class 2 Firearm','felony',60,3000,'Unlicensed/illegal possession of a Class 2 firearm (automatic, lever, or pump action). (Weapon lic: Revoked)'),
('WF04','Possession of a Class 3 Firearm','felony',90,10000,'Unlicensed/illegal possession of a Class 3 firearm (sniper, DMR, LMG, launcher). (Weapon lic: Revoked)'),
('WF05','Possession of a Class 4 Firearm','felony',120,20000,'Unlicensed/illegal possession of a Class 4 firearm (vehicle-mounted, minigun, rockets). (Weapon lic: Revoked)'),
('WF06','Unlicensed transfer of firearms, ammunition and body armor','felony',60,5000,'Selling/transferring firearms, ammo, or armor without LSPD Firearms & Licensing authorization. (Weapon lic: Revoked)'),
('WF07','Firearms Trafficking','felony',60,4500,'A single individual possessing 5 or more illegal/unlicensed firearms exceeding personal use. (Weapon lic: Revoked)'),
('WF08','Possession of a Weapon within a Correctional Facility','felony',60,5000,'Possessing or introducing a weapon while in or entering a DOC facility. (Weapon lic: Revoked)'),
('WF09','Transfer/Smuggling of Weapons into Correctional Facilities','felony',80,5000,'Transferring or smuggling weapons into or out of a DOC facility. (Weapon lic: Revoked)'),
('WF12','Battery with a Deadly Weapon','felony',60,4500,'Willful unlawful force/violence upon another through a deadly weapon. (Weapon lic: Revoked)'),
('GF01','Child Endangerment','felony',60,4000,'An act or omission exposing a child to psychological, emotional, or physical abuse. (Weapon lic: Revoked)'),
('GF02','Robbery','felony',50,2000,'Taking property off another person without uncoerced consent. (Weapon lic: Revoked)'),
('GF03','Armed Robbery','felony',60,4000,'Robbery through the use of a firearm or deadly weapon. (Weapon lic: Revoked)'),
('GF04','Sexual Assault','felony',45,3000,'Any touching of a sexual nature without consent of the victim. (Weapon lic: Revoked)'),
('GF05','Extortion','felony',45,2000,'Obtaining property from another through force or intimidation. (Weapon lic: Revoked)'),
('GF06','Blackmail','felony',45,1000,'Using force or threats to compel another person to perform an act. (Weapon lic: Revoked)'),
('GF07','Felony Fraud','felony',60,1000,'Intentional deception for gain causing > $50,000 in damages. (Weapon lic: Revoked)'),
('GF08','Illegal Gambling','felony',45,3000,'Dealing/conducting unlicensed gambling games for money or value. (Weapon lic: Revoked)'),
('GF09','Embezzlement','felony',45,3000,'Fraudulent appropriation of funds or property owned by someone else. (Weapon lic: Revoked)'),
('GF10','Grand Theft','felony',45,4000,'Taking another''s property without consent, value over $5,000. (Weapon lic: Revoked)'),
('GF11','Grand Theft Auto','felony',60,7500,'Taking someone else''s vehicle without consent. (Weapon lic: Revoked)'),
('GF12','Forgery or Counterfeiting','felony',45,3000,'Making/altering/copying seals, documents, or currency to deceive or for gain. (Weapon lic: Revoked)'),
('GF13','Arson','felony',45,1500,'Deliberately setting fire to property. (Weapon lic: Revoked)'),
('GF14','False Impersonation','felony',45,2000,'Impersonating another person to harm them or gain a benefit. (Weapon lic: Revoked)'),
('GF15','Burglary','felony',60,1000,'Illegally entering a building, vehicle, or area with intent to commit a crime. (Weapon lic: Revoked)'),
('GF16','Tampering with Evidence','felony',45,3000,'Altering, concealing, falsifying, or destroying evidence to interfere with an investigation. (Weapon lic: Revoked)'),
('GF17','Rape','felony',75,6000,'Intercourse by violence, force, fear, threat, or with those incapable of consent. (Weapon lic: Revoked)'),
('GF18','Racketeering','felony',60,3000,'Committing 2+ acts of racketeering activity within a year tied to an enterprise. (Weapon lic: Revoked)'),
('GF19','Abuse or Desecration of Dead Human Body','felony',70,3500,'Unlawfully removing, concealing, destroying, dismembering, or disturbing a dead human body/grave. (Weapon lic: Revoked)'),
('GF20','Possession of Human Body Tissue','felony',60,2000,'Possessing human tissue without being an authorized government employee/contractor on duty.'),
('GF21','Prison Break','felony',60,5000,'Attempting to break into or out of a jail/prison/containment facility. (Weapon lic: Revoked)'),
('GF22','Breach of Trust','felony',60,10000,'A trustee using entrusted government information beyond their authorized role for gain. (Weapon lic: Revoked)'),
('GF23','Grand Sales Tax Evasion','felony',40,10000,'Failing to report/pay sales tax (5%) where total tax is $50,000 or more. (Fine: $10,000 + unpaid tax +10%) (Weapon lic: Revoked)'),
('GF24','Perjury','felony',60,3000,'Knowingly providing false statements under oath to mislead a court or Congress. (Weapon lic: Revoked)'),
('GF25','Felony Contempt of Court','felony',60,5000,'Egregious or repeated willful disobedience of a court order or misconduct before a court. (Weapon lic: Revoked)'),
('GF26','Organized Assault on Government or Law Enforcement Operations','felony',45,4000,'A group of 2+ gathering to carry out an armed assault to obstruct or harm police/medical/government. (NO modifiers allowed: not attempt, accessory, aggravated, or government.) (Weapon lic: Revoked)'),
('GF27','Incitement of Violence against a Peace Officer','felony',45,4000,'Advocacy that causes the imminent unlawful killing/injuring of a peace officer (downgrades to GM27 if no harm results). (Weapon lic: Revoked)'),
('GF28','Election Fraud','felony',60,10000,'Knowingly corrupting, manipulating, or interfering with a public election. (Weapon lic: Revoked)'),
('SF01','Domestic Terrorism','felony',120,15000,'Extreme violent activity intended to intimidate a population or coerce a government. (Weapon lic: Revoked)'),
('SF02','Murder','felony',90,9000,'The premeditated or non-premeditated killing of another person. (Weapon lic: Revoked)'),
('SF03','Involuntary or Vehicular Manslaughter','felony',80,5500,'Killing another without intent but negligently, including by vehicle or aircraft. (Weapon lic: Revoked)'),
('SF04','Kidnapping','felony',70,10000,'Imprisoning or forcibly acquiring another against their will and moving them. (Weapon lic: Revoked)'),
('SF05','Torture','felony',90,12000,'Inflicting cruel and unusual bodily harm upon another person. (Weapon lic: Revoked)'),
('SF06','Possessing Destructive Devices or Explosives','felony',75,7000,'Possessing bombs, incendiary devices, or explosives intended for mass killing. (Weapon lic: Revoked)'),
('SF07','Bank Robbery','felony',70,10000,'Entering/attempting to enter a bank to deprive it of value, with or without force. (Attempt modifier does NOT apply.) (Weapon lic: Revoked)'),
('SF08','Human Trafficking','felony',75,7000,'Depriving another''s liberty with intent to obtain forced labor or services. (Weapon lic: Revoked)'),
('SF09','False Imprisonment of a Hostage','felony',70,10000,'False imprisonment of a person to avoid arrest or as a shield, increasing risk of harm. (Weapon lic: Revoked)'),
('AM01','Negligent Operation of an Aircraft','misdemeanor',35,4000,'Failing to use reasonable care while operating an aircraft, risking injury or damage. (Pilot lic: Suspended 7 Days)'),
('AM02','Operating an Unregistered Aircraft','misdemeanor',20,2000,'Operating an aircraft not registered with the SAAA. (Pilot lic: Suspended 3 Days)'),
('AM03','Operating an Aircraft without a License on your Person','misdemeanor',10,1000,'Operating an aircraft without the proper licensing on your person. (Pilot lic: Suspended 7 Days)'),
('AM04','Disrupting Airport/Aircraft Operations','misdemeanor',45,5000,'Disrupting the functional operations of an airport or air facilities. (Pilot lic: Suspended 7 Days if used)'),
('AM05','Operating an Aircraft without Proper Equipment','misdemeanor',10,1000,'Operating an aircraft that fails Minimum Safety Requirements (lights, instruments, emergency gear). (Pilot lic: Suspended 3 Days)'),
('AM06','Failure to Make Way for Emergency, State Government, or Military Aircraft','misdemeanor',25,2500,'Failure to yield/give distance to emergency or government aircraft. (Pilot lic: Suspended 3 Days)'),
('AM07','Operating an Aircraft in Controlled Airspace without Clearance','misdemeanor',20,2500,'Operating in controlled airspace without ATC clearance. (Pilot lic: Suspended 7 Days)'),
('AM08','Violating a Restricted Airspace Order or Temporary Flight Restriction','misdemeanor',35,4000,'Entering or remaining in restricted airspace or a TFR without authorization. (Pilot lic: Suspended 7 Days)'),
('AF01','Reckless Operation of an Aircraft','felony',90,10000,'Intentional disregard for life/property while operating an aircraft. (Weapon & Pilot lic: Revoked)'),
('AF02','Committing a Crime Aboard an Aircraft in Flight','felony',45,2500,'Committing any non-aviation crime aboard an aircraft in flight. (Weapon & Pilot lic: Revoked)'),
('AF03','Operating an Aircraft without an Active License','felony',60,7000,'Operating an aircraft without an active pilot''s license. (Weapon & Pilot lic: Revoked)'),
('AF04','Failure to Obey Intercepting Military or Law Enforcement Aircraft/ATC Orders','felony',70,4000,'Failure to obey instructions from intercepting aircraft or ATC. (Weapon & Pilot lic: Revoked)'),
('AF05','Violating a Prohibited Airspace Order','felony',60,3500,'Entering or remaining in prohibited airspace as designated by the SAAA. (Weapon & Pilot lic: Revoked)'),
('AF06','Transporting Dangerous Cargo','felony',45,2000,'Carrying dangerous cargo on an aircraft without SAAA written authorization. (Weapon & Pilot lic: Revoked)'),
('AF07','Drunk, Impaired, or Distracted Flying','felony',90,8000,'Operating an aircraft while intoxicated (BAC > 0.08%), impaired, or distracted. (Weapon & Pilot lic: Revoked)'),
('AF08','Aircraft Piracy','felony',120,15000,'Seizing or controlling an aircraft by force, threat, or intimidation with wrongful intent. (Weapon & Pilot lic: Revoked)'),
('AF09','Destruction of an Aircraft or Aircraft Facilities','felony',90,10000,'Damaging, destroying, or sabotaging aircraft or aircraft facilities. (Weapon & Pilot lic: Revoked) (Fine + cost of damages)'),
('AF10','Disobeying a Grounding Order','felony',90,15000,'Piloting an aircraft while under an active SAAA grounding order. (Weapon & Pilot lic: Revoked)'),
('BLB01','Breach of Minor Licensing Conditions','infraction',0,25000,'A business operating in breach of a minor licensing condition. (Regulatory citation; BLB authority only.)'),
('BLB02','Breach of Moderate Licensing Conditions','infraction',0,50000,'A business operating in breach of a moderate licensing condition. (Regulatory citation; BLB authority only.)'),
('BLB03','Breach of Major Licensing Conditions','infraction',0,100000,'A business operating in breach of a major licensing condition. (Regulatory citation; BLB authority only.)'),
('BLB04','Operating Without Valid Documents 1st Degree','infraction',0,40000,'A business operating without valid registration or the correct business license. (Regulatory citation; BLB authority only.)'),
('BLB05','Operating Without Valid Documents 2nd Degree','infraction',0,80000,'Continuing to operate without valid documents 14 days after a BLB04 citation. (Regulatory citation; BLB authority only.)'),
('BLB06','Operating Without Valid Documents 3rd Degree','infraction',0,120000,'Continuing to operate without valid documents 7 days after a BLB05 citation. (Regulatory citation; BLB authority only.)');
